### ISSUE TITLE
What could be reasons for good decoding performance before stimulus onset?

### ISSUE THREAD

**Issue by jana254** [lposani/decodanda#4]
Hi Lorenzo,

Thank you for the great package and notebooks! I am a master student working with a decoder for the first time and I am now trying to decode the action from V1 data in mice. I am using your decode in time function with pseudopopulations. They contain 1 to 20 neurons per population and around 300 trials in both conditions per neuron. The decoder shows a significantly different decoding performance than the null model already before stimulus onset. Do you know what could be the reason for this?

![image](https://github.com/lposani/decodanda/assets/81800519/7d8a8742-6099-4d69-85b1-d84de77fd3dc)

Some more details: 
In the figure above time 0 is stimulus onset, -50 is 0.5 seconds before stimulus onset and 100 is 1 second after. 

Below I show the neural responses averaged over trials and over neurons (z-scored and not z-scored). 0 is a response and 1 is no response in these figures. Here the difference between conditions before stimulus onset is very small.

![image](https://github.com/lposani/decodanda/assets/81800519/8e17efc3-8520-4951-966a-1ade02d44ef1)
![image](https://github.com/lposani/decodanda/assets/81800519/0c2913a2-61c1-4ad1-a695-2aac2b822602)

Also I used your single variable decoder on the period before stimulus onset and after stimulus onset (both 1 second) to see if it resulted in similar decoding performances. Again 0 is a response. 

Before stimulus onset: 
![image](https://github.com/lposani/decodanda/assets/81800519/99cb3cb2-d9cc-4600-9c7f-7a157b1db27e)
![image](https://github.com/lposani/decodanda/assets/81800519/100e1fe2-9d6d-46fa-a51a-3d3f5ea561c0)

After stimulus onset: 
![image](https://github.com/lposani/decodanda/assets/81800519/69a2cdf4-4062-4e2a-8439-e62bf179eded)
![image](https://github.com/lposani/decodanda/assets/81800519/1817a8d9-fb96-461e-9a9b-632806ef08c0)

Hopefully you can help me figure out why the decoder show significant results before stimulus onset. If you need any more information please let me know!

**Comment by lposani** [comment]
Hi Jana, thank you for your interest in Decodanda! Without looking into the data, it is hard to tell why the performance beats the null model before onset, as it could be due to a series of reasons. 

The first is that there is some information about future choice - this could be due e.g. to a subject's bias in choosing response or no response for any reason (e.g., personal preference, or a block of response trials that follows a block of no-response trials). In other words, neural activity - in some small part - represents future choice independently on the onset because - in small part - the subject already has decided what to do before the onset.

The second is that it comes from an artifact or a confound, such as correlations of response with another variable that is decodable before onset. If e.g. all response trials come in the first half of the experiment and all no-response come in the second half (not that this is the case, but just to make the argument), then the above-chance performance could reflect decoding of time instead of response, as these two variables are correlated.

Also, I would try to use single subjects instead of pseudo population to see whether this effect is consistent across sessions or if it comes from a few specific ones.

Let me know if you find this useful!

**Comment by jana254** [comment]
Hi Lorenzo,

Thank you for your response! 

It indeed helped to decode using single subjects as it showed which sessions had no good decoding performance at all, which had a very good decoding performance after stimulus onset and which could already decode well before stimulus onset. However, I don't know where these differences are coming from yet. 

I will think more about the possible information about future choice or artifacts that might be present in our experiment. Thank you for bringing up these possible reasons. 

Also, I was wondering if there a way to extract which neurons have the highest decoding weights from Decodanda? I think that it might be interesting to plot the PSTHs of those neurons.

**Comment by lposani** [comment]
Sure! If you are using a decoder that has the right _coef attribute (e.g. the default linear SVM), weights are saved for each cross-validation inside the Decodanda object in the attribute `self.decoding_weights` - its a dictionary in the form `variablename: (k x N) vector` where k is the number of cross validations and N the number of neurons. Please note that some neurons might get excluded due to inactivity in the decodanda constructor so sometimes the raster index and the neuron index in the weight vector do not correspond. I will likely fix this with a different logic in the next versions. Using `min_activations_per_cell = -1` in the Decodanda constructor should be a viable workaround in the meantime to make sure the index is matched.
 
Closing this, let me know if you have further questions :)
